version: '3.9'

services:

  db:
    container_name: db
    restart: unless-stopped
    image: postgres:latest
    env_file: ./db.env
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  tg-bot:
    container_name: bot
    restart: unless-stopped
    env_file: ./.env
    command: python3 main.py
    build:
      dockerfile: bot.dockerfile
    depends_on:
      - db